name: AdventurerRPG
version: '${version}'
main: plugin.adventurerRPG.Main
api-version: '1.21'
commands:
  ueststatus:
    description: 現在のクエストの状況を表示
  acceptquest:
    description: クエストを受注
  submitquest:
    description: クエストクリア
  summonNpc:
    description: NPCを召喚する
